import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import '../globals.css'
import SideBar from '@/components/shared/dashboard/side-bar'
import MobileNav from '@/components/shared/dashboard/mobile-nav'

const poppins = Poppins({ weight: ["100", "300", "500"], subsets: ["latin"]});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={`${poppins.className} bg-gray-50`}>
            <section className='flex flex-row'>
                <SideBar></SideBar>
                <main className='lg:w-[75%] w-full ml-0 lg:ml-[25%] flex-grow flex flex-col '>
                    {children}
                </main>
            </section>
            <MobileNav></MobileNav>
        </html>
    )
}
